# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build

on: [push]

jobs:
  buildJS:
    name: Validate and Build JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn

      - name: Configure Amplify
        id: configure-amplify
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          AMPLIFY: '{ "envName": "dev" }'
          AWSCLOUDFORMATIONCONFIG: '{"configLevel": "project", "useProfile": false, "accessKeyId": "$AWS_ACCESS_KEY_ID", "secretAccessKey": "$AWS_SECRET_ACCESS_KEY", "region": "$AWS_REGION" }'
          PROVIDERS: '{"awscloudformation": $AWSCLOUDFORMATIONCONFIG }'
        run: |
          npm i -g @aws-amplify/cli
          echo '{"projectPath": "'"$(pwd)"'","defaultEditor":"code","envName":"'dev'"}' > ./amplify/.config/local-env-info.json
          amplify env pull --yes dev

      # - name: configure amplify
      #   uses: ambientlight/amplify-cli-action@0.2.1
      #   with:
      #     amplify_command: configure
      #     amplify_env: dev
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: us-east-1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test -- --configuration=ci

      - name: Build
        run: yarn build -- --prod

      - name: Capacitor Sync
        run: yarn capacitor:sync

      - name: Upload the results
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: www/
      # - name: E2E
      #   run: yarn e2e -- --configuration=ci
  # buildAndroid:
  #   name: Validate and Build
  #   runs-on: ubuntu-latest
  #   needs: buildJS
