# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build

on:
  push:
    paths-ignore:
      - ".github/**"
      - "docs/**"

jobs:
  buildJS:
    name: Validate and Build JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
        environments: ["stag", "dev"]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn

      ## Original: https://github.com/ambientlight/amplify-cli-action
      - name: Configure Amplify
        id: configure-amplify
        env:
          AMPLIFY_ENV: ${{ matrix.environments }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          AMPLIFY: '{ "envName": "$AMPLIFY_ENV" }'
          AWSCLOUDFORMATIONCONFIG: '{"configLevel": "project", "useProfile": false, "accessKeyId": "$AWS_ACCESS_KEY_ID", "secretAccessKey": "$AWS_SECRET_ACCESS_KEY", "region": "$AWS_REGION" }'
          PROVIDERS: '{"awscloudformation": $AWSCLOUDFORMATIONCONFIG }'
        run: |
          npm i -g @aws-amplify/cli
          echo '{"projectPath": "'"$(pwd)"'","defaultEditor":"code","envName":"'$AMPLIFY_ENV'"}' > ./amplify/.config/local-env-info.json
          amplify env pull --yes $AMPLIFY_ENV

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test -- --configuration=ci

      - name: Build
        run: yarn build:prod

      - name: Capacitor Sync
        run: yarn capacitor:sync

      # - name: E2E
      #   run: yarn e2e -- --configuration=ci

      #################
      ### ANDROID BUILD
      #################

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build release apk
        run: |
          cd android
          ./gradlew clean assembleRelease

      # https://github.com/marketplace/actions/sign-android-release
      - name: Sign Release APK
        id: sign-android-app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      #################
      ### UPLOAD RESULTS
      #################

      - name: Upload results - JS Results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.environments }}-js
          path: www/

      - name: Upload results - APK
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.environments }}-apk
          path: ${{ steps.sign-android-app.outputs.signedReleaseFile }}
    # TODO: upload to PlayStore
    # https://github.com/marketplace/actions/upload-android-release-to-play-store
